<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../DnSpyXDX.Application/DnSpyXDX.Application.csproj" />
    <ProjectReference Include="../DnSpyXDX.Debugging/DnSpyXDX.Debugging.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="../DnSpyXDX.Debugging/CoreClrDebugger.cs" Link="CoreClrDebugger.cs" />
    <Compile Include="../DnSpyXDX.Debugging/DapConnection.cs" Link="DapConnection.cs" />
    <Compile Include="../DnSpyXDX.Debugging/DapMessageFramer.cs" Link="DapMessageFramer.cs" />
    <Compile Include="../DnSpyXDX.Debugging/DebuggerWorker.cs" Link="DebuggerWorker.cs" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="DnSpyXDX.Tests" />
  </ItemGroup>
</Project>
