<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../DnSpyXDX.Application/DnSpyXDX.Application.csproj" />
    <ProjectReference Include="../DnSpyXDX.Debugging.Protocol/DnSpyXDX.Debugging.Protocol.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="CoreClrDebugger.cs;DapConnection.cs;DapMessageFramer.cs;DebuggerWorker.cs;MonoSoftDebugger.cs;UnityMonoDebugger.cs" />
  </ItemGroup>
</Project>
