<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>DnSpyXDX.Debugger.Worker</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../DnSpyXDX.Debugging/DnSpyXDX.Debugging.csproj" />
    <ProjectReference Include="../DnSpyXDX.Debugging.CoreClr/DnSpyXDX.Debugging.CoreClr.csproj" />
    <ProjectReference Include="../DnSpyXDX.Debugging.Mono/DnSpyXDX.Debugging.Mono.csproj" />
    <ProjectReference Include="../DnSpyXDX.Debugging.UnityMono/DnSpyXDX.Debugging.UnityMono.csproj" />
    <ProjectReference Include="../DnSpyXDX.Debugging.Protocol/DnSpyXDX.Debugging.Protocol.csproj" />
  </ItemGroup>
</Project>
